<html>
    <style>
        .col-md-4{
            margin-left: 270px;
            width:60%;
        }

        .row{
            width:100%;
        }
    </style>

    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="alert alert-info">
                The target of our site is to make people socialize and share experience with each other.
                If you are searching for new friendships or new information in different categories such as wedding,
                cooking,furniture,etc our site will be the best choice for you.
            </div>
        </div>
    </div>
</html>


