<html>    
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>
    </head>
    <style>
        .container{
            width:520px;
            margin-left:400px;
        }
        .zend_form{
            color :#286090;
        }
        .text-muted{
            color :#286090;
        }
    </style>
    <div class="container"> 
        <div class="thumbnail">
            <div class="caption">
                <h1 class="text-muted">Add Thread</h1>
                <hr/>

                <?php
                echo $this->form;
                ?>
            </div>
        </div>
    </div>
</html>