<?php
$userInfo = Zend_Auth::getInstance()->getStorage()->read();
?>
<html>    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>
    </head>
    <style>
        .col-md-4{
            margin-left: 450px;
        }

        .row{
            width:100%;
        }
        .btn-danger {
            padding: 1px 8px;
            border-radius: 15px;
        }

        .btn-primary {
            padding: 1px 8px;
            border-radius: 15px;
        }

    </style>
 
    <?php if ($this->toCategoryId != NULL) { ?> 

        <div class="row">
            <div class="col-sm-6 col-md-4">
                <?php
                if (count($userInfo) != 0) {
                    if ($this->lock == "off") {
                        ?>
                        <p><a href="<?php echo $this->baseUrl() . '/thread/add/toCategoryId/' . $this->toCategoryId; ?>"  style='float: right;' class="btn btn-success" role="button">Add Thread</a></p><br><br>
                        <?php
                    }
                }
                ?>

                <?php
                if (count($this->sticky) != 0) {
                    for ($i = 0; $i < count($this->sticky); $i++) {
                        ?>

                        <div class="thumbnail">
                            <div class="caption">
                                <p style="text-align: center; color:red ">
                                    <span   style="color:red" class="glyphicon glyphicon-star-empty"></span> <span style="color:red" class="glyphicon glyphicon-star-empty"></span> <span style="color:red" class="glyphicon glyphicon-star-empty"></span>
                                    Pinned Thread 
                                    <span  style="color:red" class="glyphicon glyphicon-star-empty"></span> <span style="color:red" class="glyphicon glyphicon-star-empty"></span> <span style="color:red" class="glyphicon glyphicon-star-empty"></span>
                                </p>
                                <h3><a href="<?php echo $this->baseUrl() . '/thread/display/id/' . $this->sticky[$i]['id'] . '/toCategoryId/' . $this->toCategoryId; ?>" ><?php echo $this->sticky[$i]['title'] ?></a></h3>
                                <p><?php echo substr($this->sticky[$i]['body'], 0, 15) . "..."; ?></p>
                            </div>

                        </div>
                        <?php
                    }
                }
                ?>
            </div>

            <div class="col-sm-6 col-md-4">

                <?php for ($i = 0; $i < count($this->unsticky); $i++) {
                    ?>
                    <div class="thumbnail">
                        <div class="caption">
                            <h3><a href="<?php echo $this->baseUrl() . '/thread/display/id/' . $this->unsticky[$i]['id'] . '/toCategoryId/' . $this->toCategoryId; ?>" ><?php echo $this->unsticky[$i]['title'] ?></a></h3>
                            <p><?php echo substr($this->unsticky[$i]['body'], 0, 15) . "..."; ?></p>
                        </div>
         
                <?php } ?>
            </div>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span>  Error ! Page Not Found</div>
    <?php } ?>
</html>