<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>

	<div class="welcome" align="center">
 			<h2 class="brand-before">
                        <small>Welcome to</small>
            </h2>
            <h1 class="brand-name">RNR</h1>
	</div>
<?php 
   $DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT'];
    include ($DOCUMENT_ROOT.'/RNR/public/design/slider.php');
?>